# Generated by Django 3.1.4 on 2021-01-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_html', '0002_importcss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportCSS',
        ),
    ]
