# Generated by Django 3.1.5 on 2021-01-29 02:53

import auth_users.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(max_length=8, validators=[auth_users.validators.no_future_date], verbose_name='date of birth')),
                ('image_add', models.ImageField(upload_to='avatars', validators=[auth_users.validators.validate_image], verbose_name='avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
