# Generated by Django 3.1.4 on 2021-01-28 17:45

import auth_users.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image_add',
            field=models.ImageField(upload_to='avatars', validators=[auth_users.validators.validate_image], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
