# Generated by Django 3.1.4 on 2021-01-14 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of Article')),
                ('content', models.TextField(verbose_name='Content of Article')),
                ('pub_date', models.DateField(default=datetime.datetime, verbose_name='Date')),
            ],
        ),
    ]
