# Generated by Django 3.1.4 on 2021-01-19 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of Article')),
                ('content', models.TextField(verbose_name='Content of Article')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 11, 36, 9, 514862), verbose_name='Date')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Image of Article')),
            ],
        ),
    ]
