# Generated by Django 3.1.5 on 2021-01-29 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 3, 7, 47, 225285), verbose_name='Date'),
        ),
    ]
