# Generated by Django 3.1.5 on 2021-01-29 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210129_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 3, 26, 2, 673662), verbose_name='Date'),
        ),
    ]
