# Generated by Django 3.1.4 on 2021-01-19 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210119_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 37, 59, 493374), verbose_name='Date'),
        ),
    ]
