# Generated by Django 3.1.4 on 2021-01-19 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210119_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 39, 12, 354920), verbose_name='Date'),
        ),
    ]
