# Generated by Django 3.1.4 on 2021-01-14 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210114_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 12, 36, 12, 452788), verbose_name='Date'),
        ),
    ]
