# Generated by Django 3.1.4 on 2021-01-19 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210119_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 48, 49, 211127), verbose_name='Date'),
        ),
    ]
