# Generated by Django 3.1.5 on 2021-01-29 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210129_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 4, 0, 59, 917067), verbose_name='Date'),
        ),
    ]
