# Generated by Django 3.1.4 on 2021-01-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210114_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 12, 37, 53, 908584), verbose_name='Date'),
        ),
    ]
