# Generated by Django 3.1.4 on 2021-01-16 20:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210114_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, height_field=300, upload_to='', verbose_name='Images of Article', width_field=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 21, 9, 39, 803591), verbose_name='Date'),
        ),
    ]
