# Generated by Django 3.1.4 on 2021-01-19 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210119_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 14, 10, 54, 510589), verbose_name='Date'),
        ),
    ]
