# Generated by Django 3.1.4 on 2021-01-19 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210119_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 15, 12, 6, 998370), verbose_name='Date'),
        ),
    ]
