# Generated by Django 3.1.4 on 2021-01-19 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210119_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 15, 13, 8, 510591), verbose_name='Date'),
        ),
    ]
