# Generated by Django 3.1.4 on 2021-01-26 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20210127_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 0, 55, 11, 762462), verbose_name='Date'),
        ),
    ]
