# Generated by Django 3.1.4 on 2021-01-27 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20210127_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 1, 22, 13, 631149), verbose_name='Date'),
        ),
    ]
