# Generated by Django 3.1.4 on 2021-01-28 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20210128_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 15, 57, 52, 295178), verbose_name='Date'),
        ),
    ]
