# Generated by Django 3.1.4 on 2021-01-28 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20210128_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 18, 7, 12, 533907), verbose_name='Date'),
        ),
    ]
