# Generated by Django 3.1.4 on 2021-01-17 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20210117_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 11, 23, 22, 958921), verbose_name='Date'),
        ),
    ]
