# Generated by Django 3.1.4 on 2021-01-17 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20210117_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 11, 25, 29, 382967), verbose_name='Date'),
        ),
    ]
